Done!
mate-academy/py-elves-and-dwarves pull request #700
Opened 2023-10-22 18:06 UTC by PyCore23

2023-10-23 10:01 UTC, Dimosphen1 requested changes
Several changes were requested.

2023-10-23 10:01 UTC, Dimosphen1 commented on app/players/elves/elf.py
> +class Elf(Player):
The `Elf` class does not implement all abstract methods of `Player`, so it should be abstract as well. Inherit `Elf` from `ABC` as well.

2023-11-24 12:31 UTC, pavlejviki requested changes

2023-11-24 12:31 UTC, pavlejviki commented on app/players/dwarves/dwarf.py
> +    def get_rating(self) -> str:
it is not what you were supposed to do. instead of implementing this methods, just inherid from ABC
`
class Dwarf(Player, ABC):`

2023-11-24 12:31 UTC, pavlejviki commented on app/players/elves/elf.py
> +        return "NotImplemented"
remove redundant methods. inherit from ABC

2024-01-13 15:46 UTC, vsmutok requested changes
Well Done!

2024-01-13 15:46 UTC, vsmutok approved these changes

2024-05-17 10:04 UTC, closed without merging